@echo off
echo Running database migration...
cd /d "%~dp0"

echo Step 1: Generating Prisma client...
npx prisma generate

echo Step 2: Creating migration...
npx prisma migrate dev --name add-contact-management

echo Step 3: Checking migration status...
npx prisma migrate status

echo Migration completed! Press any key to exit...
pause 